---
name: Auto-add needs-triage labels to new issues


on:
  issues:
    types: [opened]


permissions:
  issues: write


jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - run: >-
          gh issue
          edit ${{ github.event.issue.number }}
          --add-label needs-triage
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
